language: nix

env:
  GENERATING_AMI=1

install:
  - nix-env -iA nixpkgs.nixopsUnstable
  - nixops create deployments/cardano.nix -d csl
  - nixops create deployments/timewarp.nix -d tw
  - nixops create deployments/infrastructure.nix -d inf
script:
  - ./CardanoCSL.hs --help
  - ./TimeWarp.hs --help
  - ./Infra.hs --help
  - nix-instantiate default.nix -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/763e21e982370f67c126f92a1113ea949db3b6e0.tar.gz
  - nixops deploy -d csl --evaluate-only
  - nixops deploy -d tw --evaluate-only
  - nixops deploy -d inf --evaluate-only

notifications:
  email: false
  slack:
    secure: "ir2BctpXIP5h7isDeJk04HFfVzp7AFjzAB+WD8G31I+llISXuKq+KWkbkQSFe8/p74rMAnpaInJ9vlKHLj2AQ9KzTTEwzWevupXHJQ0VXgt4Jftl6aE42PZPTRZ9BrmNvuodKBflk0DAxWczJnkv7qHWvmWnBT3D648rWM4tsAgPKcOFUxamxUYXgq5RWVpNbERjFk3oM1LpfPPHw/hxrwOgj6TMReEDWYmV+7Z9QH29Kt28L6CH4E5a9ZTGErq0o8dP4NM8t2ZSLXcVpiA6gdyeMnm9xgcsjA4eAGZOgF+RgxLZfh0uI4Ml4eiueRQG/pDZjM4L+sg9Mpuj+8iZQxiXernPyQuIvQwK/CxV3KR7+Aenl/7Fh3Z6FXwD2ReqfxSNuh3NWa97sD7KvECK0BrWwtprdaQpGyqEhpIObHNCtHUS2//2BxAFuLHcnJuHdJZZimfm4meR2Jbhj52EXpQpKRHViDEcgIXtA04+NKsgYwldXF6SIyFsv+/LpbKO9CyCSrZ405VtN0kN9KzISnMHP0yJitVpE1DVtfRb8hkW899r9E6c5eX7fIcZHSXogcxm45dKFTymGUxamsYlOntleKakKwTsUIPS04AkPkzMXEYHYUAE+UdkVjVaCkhyVao9EwBwxCHAMowNXHavTvZdOfy7eeX5CRTBCdbJzwI="
