language: nix

env:
  NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/c0b1e8a5fb174cd405dcca9f7fec275714ad9f4b.tar.gz

install:
  - nix-env -iA nixopsUnstable -f '<nixpkgs>'
  - touch static/datadog-{api,application}.secret
  - echo "secret" > static/tarsnap-cardano-deployer.secret
  - mkdir keys
  - touch keys/key{0,1,2,3,4,5,6,7,8,9,10,11,12,13,41}.sk
script:
  - nixops --version
  # check all scripts compile
  - ./CardanoCSL.hs --help
  - ./TimeWarp.hs --help
  - ./Infra.hs --help
  - ./scripts/ctl.hs --help
  # check all packages build
  - nix-instantiate jobsets/cardano.nix --show-trace
  # check deploy evaluations
  - nixops create deployments/{cardano-nodes,cardano-nodes-target-aws,cardano-nodes-env-production,cardano-explorer,cardano-explorer-target-aws,cardano-explorer-env-production,report-server,report-server-target-aws,report-server-env-production,keypairs}.nix -d csl-production
  - nixops create deployments/{cardano-nodes,cardano-nodes-target-aws,cardano-nodes-env-staging,cardano-explorer,cardano-explorer-target-aws,cardano-explorer-env-staging,report-server,report-server-target-aws,report-server-env-staging,keypairs}.nix -d csl-staging
  - nixops create deployments/{cardano-nodes,cardano-nodes-target-aws,cardano-explorer,cardano-explorer-target-aws,report-server,report-server-target-aws,keypairs}.nix -d csl
  - nixops create deployments/{cardano-explorer,cardano-explorer-target-aws,cardano-explorer-env-staging,cardano-explorer-env-development,keypairs}.nix -d csl-explorer-staging
  - nixops create deployments/timewarp{,-target-aws}.nix deployments/keypairs.nix -d tw
  - nixops create deployments/{infrastructure,infrastructure-target-aws,infrastructure-env-production,keypairs}.nix -d inf
  - nixops deploy -d csl --evaluate-only --show-trace
  - nixops deploy -d csl-production --evaluate-only --show-trace
  - nixops deploy -d csl-staging --evaluate-only --show-trace
  - nixops deploy -d csl-explorer-staging --evaluate-only --show-trace
  - nixops deploy -d tw --evaluate-only --show-trace
  - nixops deploy -d inf --evaluate-only --show-trace

notifications:
  email: false
  slack:
    secure: "ir2BctpXIP5h7isDeJk04HFfVzp7AFjzAB+WD8G31I+llISXuKq+KWkbkQSFe8/p74rMAnpaInJ9vlKHLj2AQ9KzTTEwzWevupXHJQ0VXgt4Jftl6aE42PZPTRZ9BrmNvuodKBflk0DAxWczJnkv7qHWvmWnBT3D648rWM4tsAgPKcOFUxamxUYXgq5RWVpNbERjFk3oM1LpfPPHw/hxrwOgj6TMReEDWYmV+7Z9QH29Kt28L6CH4E5a9ZTGErq0o8dP4NM8t2ZSLXcVpiA6gdyeMnm9xgcsjA4eAGZOgF+RgxLZfh0uI4Ml4eiueRQG/pDZjM4L+sg9Mpuj+8iZQxiXernPyQuIvQwK/CxV3KR7+Aenl/7Fh3Z6FXwD2ReqfxSNuh3NWa97sD7KvECK0BrWwtprdaQpGyqEhpIObHNCtHUS2//2BxAFuLHcnJuHdJZZimfm4meR2Jbhj52EXpQpKRHViDEcgIXtA04+NKsgYwldXF6SIyFsv+/LpbKO9CyCSrZ405VtN0kN9KzISnMHP0yJitVpE1DVtfRb8hkW899r9E6c5eX7fIcZHSXogcxm45dKFTymGUxamsYlOntleKakKwTsUIPS04AkPkzMXEYHYUAE+UdkVjVaCkhyVao9EwBwxCHAMowNXHavTvZdOfy7eeX5CRTBCdbJzwI="
